### PR TITLE
layout and static pages (2)

### PR DESCRIPTION
**Pull request by sangpt**

### CODE REVIEW

**Comment by sangpt** [comment]
------------------------------------------
[x] Build Fail!
------------------------------------------

[o] eslint: success
[o] scss-lint: success
[o] rubocop: success
[o] rails_best_practices: success
[o] reek: success
[o] bundle-audit: success
[o] brakeman: success
[x] rspec: failed

**Comment by sangpt** [comment]
ready

**Comment by huongnguyenmta** [comment]
commented

**Comment by huongnguyenmta** [comment]
commented

**Comment by sangpt** [comment]
ready

**Pull request merged**
